apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: datastax-credentials
  namespace: gcp-python-cassandra
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/$PROJECT_ID/secrets/datastax_connect_bundle_1/versions/1"
        path: "secure-connect-cassandra-db-1.zip"
      - resourceName: "projects/$PROJECT_ID/secrets/datastax_client_id/versions/1"
        path: "client_id.txt"
      - resourceName: "projects/$PROJECT_ID/secrets/datastax_client_secret/versions/1"
        path: "client_secret.txt"