apiVersion: v1
kind: Service
metadata:
  name: python-cassandra
  namespace: gcp-python-cassandra
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: python-cassandra